CREATE TABLE Album (
  AlbumId number NOT NULL,
  Title varchar(100),
  ArtistId number,
  Column1 BLOB
);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(1, 'For Those About To Rock We Salute You', 1, null);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(2, 'Balls to the Wall', 2, null);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(3, 'Restless and Wild', 2, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(4, 'Let There Be Rock', 1, 0x657771657771);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(5, 'Big Ones', 3, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(6, 'Jagged Little Pill', 4, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(7, 'Facelift', 5, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(8, 'Warner 25 Anos', 6, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(9, 'Plays Metallica By Four Cellos', 7, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(10, 'Audioslave', 8, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(11, 'Out Of Exile', 8, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(12, 'BackBeat Soundtrack', 9, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(13, 'The Best Of Billy Cobham', 10, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(14, 'Alcohol Fueled Brewtality Live! [Disc 1]', 11, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(15, 'Alcohol Fueled Brewtality Live! [Disc 2]', 11, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(16, 'Black Sabbath', 12, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(17, 'Black Sabbath Vol. 4 (Remaster)', 12, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(18, 'Body Count', 13, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(19, 'Chemical Wedding', 14, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(20, 'The Best Of Buddy Guy - The Millenium Collection', 15, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(21, 'Prenda Minha', 16, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(22, 'Sozinho Remix Ao Vivo', 16, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(23, 'Minha Historia', 17, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(24, 'Afrociberdelia', 18, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(25, 'Da Lama Ao Caos', 18, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(26, 'Acústico MTV [Live]', 19, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(27, 'Cidade Negra - Hits', 19, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(28, 'Na Pista', 20, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(29, 'Axé Bahia 2001', 21, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(30, 'BBC Sessions [Disc 1] [Live]', 22, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(31, 'Bongo Fury', 23, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(32, 'Carnaval 2001', 21, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(33, 'Chill: Brazil (Disc 1)', 24, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(34, 'Chill: Brazil (Disc 2)', 6, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(35, 'Garage Inc. (Disc 1)', 50, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(36, 'Greatest Hits II', 51, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(37, 'Greatest Kiss', 52, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(38, 'Heart of the Night', 53, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(39, 'International Superhits', 54, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(40, 'Into The Light', 55, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(41, 'Meus Momentos', 56, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(42, 'Minha História', 57, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(43, 'MK III The Final Concerts [Disc 1]', 58, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(44, 'Physical Graffiti [Disc 1]', 22, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(45, 'Sambas De Enredo 2001', 21, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(46, 'Supernatural', 59, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(47, 'The Best of Ed Motta', 37, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(48, 'The Essential Miles Davis [Disc 1]', 68, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(49, 'The Essential Miles Davis [Disc 2]', 68, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(50, 'The Final Concerts (Disc 2)', 58, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(51, 'Up An'' Atom', 69, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(52, 'Vinícius De Moraes - Sem Limite', 70, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(53, 'Vozes do MPB', 21, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(54, 'Chronicle, Vol. 1', 76, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(55, 'Chronicle, Vol. 2', 76, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(56, 'Cássia Eller - Coleção Sem Limite [Disc 2]', 77, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(57, 'Cássia Eller - Sem Limite [Disc 1]', 77, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(58, 'Come Taste The Band', 58, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(59, 'Deep Purple In Rock', 58, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(60, 'Fireball', 58, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(61, 'Knocking at Your Back Door: The Best Of Deep Purple in the 80''s', 58, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(62, 'Machine Head', 58, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(63, 'Purpendicular', 58, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(64, 'Slaves And Masters', 58, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(65, 'Stormbringer', 58, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(66, 'The Battle Rages On', 58, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(67, 'Vault: Def Leppard''s Greatest Hits', 78, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(68, 'Outbreak', 79, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(69, 'Djavan Ao Vivo - Vol. 02', 80, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(70, 'Djavan Ao Vivo - Vol. 1', 80, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(71, 'Elis Regina-Minha História', 41, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(72, 'The Cream Of Clapton', 81, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(73, 'Unplugged', 81, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(74, 'Album Of The Year', 82, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(75, 'Angel Dust', 82, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(76, 'King For A Day Fool For A Lifetime', 82, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(77, 'The Real Thing', 82, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(78, 'Deixa Entrar', 83, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(79, 'In Your Honor [Disc 1]', 84, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(80, 'In Your Honor [Disc 2]', 84, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(81, 'One By One', 84, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(82, 'The Colour And The Shape', 84, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(83, 'My Way: The Best Of Frank Sinatra [Disc 1]', 85, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(84, 'Roda De Funk', 86, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(85, 'As Canções de Eu Tu Eles', 27, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(86, 'Quanta Gente Veio Ver (Live)', 27, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(87, 'Quanta Gente Veio ver--Bônus De Carnaval', 27, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(88, 'Faceless', 87, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(89, 'American Idiot', 54, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(90, 'Appetite for Destruction', 88, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(91, 'Use Your Illusion I', 88, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(92, 'Use Your Illusion II', 88, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(93, 'Blue Moods', 89, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(94, 'A Matter of Life and Death', 90, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(95, 'A Real Dead One', 90, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(96, 'A Real Live One', 90, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(97, 'Brave New World', 90, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(98, 'Dance Of Death', 90, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(99, 'Fear Of The Dark', 90, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(100, 'Iron Maiden', 90, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(101, 'Killers', 90, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(102, 'Live After Death', 90, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(103, 'Live At Donington 1992 (Disc 1)', 90, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(104, 'Live At Donington 1992 (Disc 2)', 90, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(105, 'No Prayer For The Dying', 90, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(106, 'Piece Of Mind', 90, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(107, 'Powerslave', 90, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(108, 'Rock In Rio [CD1]', 90, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(109, 'Rock In Rio [CD2]', 90, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(110, 'Seventh Son of a Seventh Son', 90, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(111, 'Somewhere in Time', 90, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(112, 'The Number of The Beast', 90, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(113, 'The X Factor', 90, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(114, 'Virtual XI', 90, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(115, 'Sex Machine', 91, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(116, 'Emergency On Planet Earth', 92, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(117, 'Synkronized', 92, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(118, 'The Return Of The Space Cowboy', 92, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(119, 'Get Born', 93, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(120, 'Are You Experienced?', 94, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(121, 'Surfing with the Alien (Remastered)', 95, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(122, 'Jorge Ben Jor 25 Anos', 46, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(123, 'Jota Quest-1995', 96, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(124, 'Cafezinho', 97, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(125, 'Living After Midnight', 98, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(126, 'Unplugged [Live]', 52, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(127, 'BBC Sessions [Disc 2] [Live]', 22, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(128, 'Coda', 22, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(129, 'Houses Of The Holy', 22, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(130, 'In Through The Out Door', 22, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(131, 'IV', 22, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(132, 'Led Zeppelin I', 22, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(133, 'Led Zeppelin II', 22, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(134, 'Led Zeppelin III', 22, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(135, 'Physical Graffiti [Disc 2]', 22, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(136, 'Presence', 22, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(137, 'The Song Remains The Same (Disc 1)', 22, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(138, 'The Song Remains The Same (Disc 2)', 22, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(139, 'A TempestadeTempestade Ou O Livro Dos Dias', 99, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(140, 'Mais Do Mesmo', 99, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(141, 'Greatest Hits', 100, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(142, 'Lulu Santos - RCA 100 Anos De Música - Álbum 01', 101, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(143, 'Lulu Santos - RCA 100 Anos De Música - Álbum 02', 101, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(144, 'Misplaced Childhood', 102, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(145, 'Barulhinho Bom', 103, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(146, 'Seek And Shall Find: More Of The Best (1963-1981)', 104, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(147, 'The Best Of Men At Work', 105, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(148, 'Black Album', 50, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(149, 'Garage Inc. (Disc 2)', 50, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(150, 'Kill ''Em All', 50, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(151, 'Load', 50, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(152, 'Master Of Puppets', 50, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(153, 'ReLoad', 50, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(154, 'Ride The Lightning', 50, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(155, 'St. Anger', 50, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(156, '...And Justice For All', 50, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(157, 'Miles Ahead', 68, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(158, 'Milton Nascimento Ao Vivo', 42, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(159, 'Minas', 42, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(160, 'Ace Of Spades', 106, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(161, 'Demorou...', 108, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(162, 'Motley Crue Greatest Hits', 109, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(163, 'From The Muddy Banks Of The Wishkah [Live]', 110, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(164, 'Nevermind', 110, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(165, 'Compositores', 111, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(166, 'Olodum', 112, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(167, 'Acústico MTV', 113, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(168, 'Arquivo II', 113, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(169, 'Arquivo Os Paralamas Do Sucesso', 113, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(170, 'Bark at the Moon (Remastered)', 114, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(171, 'Blizzard of Ozz', 114, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(172, 'Diary of a Madman (Remastered)', 114, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(173, 'No More Tears (Remastered)', 114, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(174, 'Tribute', 114, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(175, 'Walking Into Clarksdale', 115, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(176, 'Original Soundtracks 1', 116, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(177, 'The Beast Live', 117, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(178, 'Live On Two Legs [Live]', 118, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(179, 'Pearl Jam', 118, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(180, 'Riot Act', 118, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(181, 'Ten', 118, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(182, 'Vs.', 118, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(183, 'Dark Side Of The Moon', 120, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(184, 'Os Cães Ladram Mas A Caravana Não Pára', 121, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(185, 'Greatest Hits I', 51, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(186, 'News Of The World', 51, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(187, 'Out Of Time', 122, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(188, 'Green', 124, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(189, 'New Adventures In Hi-Fi', 124, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(190, 'The Best Of R.E.M.: The IRS Years', 124, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(191, 'Cesta Básica', 125, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(192, 'Raul Seixas', 126, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(193, 'Blood Sugar Sex Magik', 127, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(194, 'By The Way', 127, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(195, 'Californication', 127, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(196, 'Retrospective I (1974-1980)', 128, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(197, 'Santana - As Years Go By', 59, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(198, 'Santana Live', 59, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(199, 'Maquinarama', 130, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(200, 'O Samba Poconé', 130, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(201, 'Judas 0: B-Sides and Rarities', 131, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(202, 'Rotten Apples: Greatest Hits', 131, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(203, 'A-Sides', 132, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(204, 'Morning Dance', 53, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(205, 'In Step', 133, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(206, 'Core', 134, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(207, 'Mezmerize', 135, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(208, '[1997] Black Light Syndrome', 136, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(209, 'Live [Disc 1]', 137, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(210, 'Live [Disc 2]', 137, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(211, 'The Singles', 138, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(212, 'Beyond Good And Evil', 139, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(213, 'Pure Cult: The Best Of The Cult (For Rockers, Ravers, Lovers & Sinners) [UK]', 139, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(214, 'The Doors', 140, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(215, 'The Police Greatest Hits', 141, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(216, 'Hot Rocks, 1964-1971 (Disc 1)', 142, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(217, 'No Security', 142, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(218, 'Voodoo Lounge', 142, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(219, 'Tangents', 143, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(220, 'Transmission', 143, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(221, 'My Generation - The Very Best Of The Who', 144, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(222, 'Serie Sem Limite (Disc 1)', 145, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(223, 'Serie Sem Limite (Disc 2)', 145, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(224, 'Acústico', 146, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(225, 'Volume Dois', 146, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(226, 'Battlestar Galactica: The Story So Far', 147, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(227, 'Battlestar Galactica, Season 3', 147, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(228, 'Heroes, Season 1', 148, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(229, 'Lost, Season 3', 149, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(230, 'Lost, Season 1', 149, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(231, 'Lost, Season 2', 149, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(232, 'Achtung Baby', 150, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(233, 'All That You Can''t Leave Behind', 150, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(234, 'B-Sides 1980-1990', 150, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(235, 'How To Dismantle An Atomic Bomb', 150, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(236, 'Pop', 150, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(237, 'Rattle And Hum', 150, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(238, 'The Best Of 1980-1990', 150, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(239, 'War', 150, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(240, 'Zooropa', 150, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(241, 'UB40 The Best Of - Volume Two [UK]', 151, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(242, 'Diver Down', 152, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(243, 'The Best Of Van Halen, Vol. I', 152, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(244, 'Van Halen', 152, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(245, 'Van Halen III', 152, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(246, 'Contraband', 153, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(247, 'Vinicius De Moraes', 72, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(248, 'Ao Vivo [IMPORT]', 155, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(249, 'The Office, Season 1', 156, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(250, 'The Office, Season 2', 156, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(251, 'The Office, Season 3', 156, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(252, 'Un-Led-Ed', 157, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(253, 'Battlestar Galactica (Classic), Season 1', 158, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(254, 'Aquaman', 159, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(255, 'Instant Karma: The Amnesty International Campaign to Save Darfur', 150, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(256, 'Speak of the Devil', 114, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(257, '20th Century Masters - The Millennium Collection: The Best of Scorpions', 179, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(258, 'House of Pain', 180, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(259, 'Radio Brasil (O Som da Jovem Vanguarda) - Seleccao de Henrique Amaro', 36, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(260, 'Cake: B-Sides and Rarities', 196, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(261, 'LOST, Season 4', 149, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(262, 'Quiet Songs', 197, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(263, 'Muso Ko', 198, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(264, 'Realize', 199, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(265, 'Every Kind of Light', 200, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(266, 'Duos II', 201, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(267, 'Worlds', 202, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(268, 'The Best of Beethoven', 203, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(269, 'Temple of the Dog', 204, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(270, 'Carry On', 205, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(271, 'Revelations', 8, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(272, 'Adorate Deum: Gregorian Chant from the Proper of the Mass', 206, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(273, 'Allegri: Miserere', 207, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(274, 'Pachelbel: Canon & Gigue', 208, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(275, 'Vivaldi: The Four Seasons', 209, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(276, 'Bach: Violin Concertos', 210, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(277, 'Bach: Goldberg Variations', 211, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(278, 'Bach: The Cello Suites', 212, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(279, 'Handel: The Messiah (Highlights)', 213, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(280, 'The World of Classical Favourites', 214, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(281, 'Sir Neville Marriner: A Celebration', 215, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(282, 'Mozart: Wind Concertos', 216, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(283, 'Haydn: Symphonies 99 - 104', 217, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(284, 'Beethoven: Symhonies Nos. 5 & 6', 218, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(285, 'A Soprano Inspired', 219, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(286, 'Great Opera Choruses', 220, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(287, 'Wagner: Favourite Overtures', 221, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(288, 'Fauré: Requiem, Ravel: Pavane & Others', 222, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(289, 'Tchaikovsky: The Nutcracker', 223, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(290, 'The Last Night of the Proms', 224, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(291, 'Puccini: Madama Butterfly - Highlights', 225, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(292, 'Holst: The Planets, Op. 32 & Vaughan Williams: Fantasies', 226, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(293, 'Pavarotti''s Opera Made Easy', 227, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(294, 'Great Performances - Barber''s Adagio and Other Romantic Favorites for Strings', 228, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(295, 'Carmina Burana', 229, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(296, 'A Copland Celebration, Vol. I', 230, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(297, 'Bach: Toccata & Fugue in D Minor', 231, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(298, 'Prokofiev: Symphony No.1', 232, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(299, 'Scheherazade', 233, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(300, 'Bach: The Brandenburg Concertos', 234, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(301, 'Chopin: Piano Concertos Nos. 1 & 2', 235, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(302, 'Mascagni: Cavalleria Rusticana', 236, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(303, 'Sibelius: Finlandia', 237, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(304, 'Beethoven Piano Sonatas: Moonlight & Pastorale', 238, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(305, 'Great Recordings of the Century - Mahler: Das Lied von der Erde', 240, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(306, 'Elgar: Cello Concerto & Vaughan Williams: Fantasias', 241, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(307, 'Adams, John: The Chairman Dances', 242, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(308, 'Tchaikovsky: 1812 Festival Overture, Op.49, Capriccio Italien & Beethoven: Wellington''s Victory', 243, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(309, 'Palestrina: Missa Papae Marcelli & Allegri: Miserere', 244, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(310, 'Prokofiev: Romeo & Juliet', 245, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(311, 'Strauss: Waltzes', 226, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(312, 'Berlioz: Symphonie Fantastique', 245, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(313, 'Bizet: Carmen Highlights', 246, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(314, 'English Renaissance', 247, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(315, 'Handel: Music for the Royal Fireworks (Original Version 1749)', 208, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(316, 'Grieg: Peer Gynt Suites & Sibelius: Pelléas et Mélisande', 248, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(317, 'Mozart Gala: Famous Arias', 249, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(318, 'SCRIABIN: Vers la flamme', 250, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(319, 'Armada: Music from the Courts of England and Spain', 251, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(320, 'Mozart: Symphonies Nos. 40 & 41', 248, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(321, 'Back to Black', 252, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(322, 'Frank', 252, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(323, 'Carried to Dust (Bonus Track Version)', 253, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(324, 'Beethoven: Symphony No. 6 ''Pastoral'' Etc.', 254, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(325, 'Bartok: Violin & Viola Concertos', 255, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(326, 'Mendelssohn: A Midsummer Night''s Dream', 256, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(327, 'Bach: Orchestral Suites Nos. 1 - 4', 257, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(328, 'Charpentier: Divertissements, Airs & Concerts', 258, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(329, 'South American Getaway', 259, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(330, 'Górecki: Symphony No. 3', 260, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(331, 'Purcell: The Fairy Queen', 261, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(332, 'The Ultimate Relexation Album', 262, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(333, 'Purcell: Music for the Queen Mary', 263, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(334, 'Weill: The Seven Deadly Sins', 264, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(335, 'J.S. Bach: Chaconne, Suite in E Minor, Partita in E Major & Prelude, Fugue and Allegro', 265, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(336, 'Prokofiev: Symphony No.5 & Stravinksy: Le Sacre Du Printemps', 248, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(337, 'Szymanowski: Piano Works, Vol. 1', 266, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(338, 'Nielsen: The Six Symphonies', 267, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(339, 'Great Recordings of the Century: Paganini''s 24 Caprices', 268, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(340, 'Liszt - 12 Études D''Execution Transcendante', 269, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(341, 'Great Recordings of the Century - Shubert: Schwanengesang, 4 Lieder', 270, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(342, 'Locatelli: Concertos for Violin, Strings and Continuo, Vol. 3', 271, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(343, 'Respighi:Pines of Rome', 226, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(344, 'Schubert: The Late String Quartets & String Quintet (3 CD''s)', 272, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(345, 'Monteverdi: L''Orfeo', 273, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(346, 'Mozart: Chamber Music', 274, NULL);
INSERT INTO Album (AlbumId, Title, ArtistId, Column1) VALUES(347, 'Koyaanisqatsi (Soundtrack from the Motion Picture)', 275, NULL);
commit;
